# Øving 5
We start by loading the dataset into a pandas file:

In [6]:
import pandas as pd

file = pd.read_csv("dataset/agaricus-lepiota.data")
file.describe()

,edibility,cap-shape,cap-surface,cap-color,bruises?,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
count,8124,8124,8124,8124,8124,8124,8124,8124,8124,8124,...,8124,8124,8124,8124,8124,8124,8124,8124,8124,8124
unique,2,6,4,10,2,9,2,2,2,12,...,4,9,9,1,4,3,5,9,6,7
top,e,x,y,n,f,n,f,c,b,b,...,s,w,w,p,w,o,p,w,v,d
freq,4208,3656,3244,2284,4748,3528,7914,6812,5612,1728,...,4936,4464,4384,8124,7924,7488,3968,2388,4040,3148

We extract just the habitat and edibility features, and group them by the different types of habitat:

In [5]:
habitat_edibility = file[["habitat", "edibility"]].groupby(["habitat"])

habitat_edibility.describe()

        edibility
            count unique top  freq
habitat
d            3148      2   e  1880
g            2148      2   e  1408
l             832      2   p   592
m             292      2   e   256
p            1144      2   p  1008
u             368      2   p   272
w             192      1   e   192

We start by extracting each feature:

In [14]:
print(file.columns.values)

['edibility' 'cap-shape' 'cap-surface' 'cap-color' 'bruises?' 'odor'
 'gill-attachment' 'gill-spacing' 'gill-size' 'gill-color' 'stalk-shape'
 'stalk-root' 'stalk-surface-above-ring' 'stalk-surface-below-ring'
 'stalk-color-above-ring' 'stalk-color-below-ring' 'veil-type'
 'veil-color' 'ring-number' 'ring-type' 'spore-print-color' 'population'
 'habitat']

In [17]:
i=0
features = []
for feature in file.column.values:
    features[i] = filez[feature]
    i += 1

print(features)

AttributeError: 'DataFrame' object has no attribute 'column'